version: "3"
services:

  mysql:
    container_name: mysql
    image: mysql:8.0
    environment:
      - MYSQL_ROOT_PASSWORD=Root@2021
      - MYSQL_DATABASE=P9
      - MYSQL_USER=user
      - MYSQL_PASSWORD=User@2021
    ports:
      - "3306:3306"
    healthcheck:
      test: "/usr/bin/mysql --user=root --password=Root@2021 --execute \"SHOW DATABASES;\""
      interval: 3s
      timeout: 1s
      retries: 10
    networks:
      docker-net:
        ipv4_address: ${IP_SQL}

  searchpatient:
    container_name: searchpatient
    image: searchpatient
    ports:
      - "9104:9104"
    networks:
      docker-net:
        ipv4_address: ${IP_SEARCHPATIENT}
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://${IP_SQL}:3306/P9?serverTimezone=UTC
    restart: on-failure
    depends_on:
      mysql:
        condition: service_healthy

networks:
  docker-net:
    external: true
    driver: bridge

